from django.shortcuts import render
# For HttpResponse function
from django.http import HttpResponse
# For Db connections: connection is used for default Db and connections for other Dbs
from django.db import connection
from django.db import connections
# For simplejson output during return stage
import json as simplejson

# Create your views here.

# View 1: Default welcome note.
def index_view(request):
    return HttpResponse("Welcome to National Innovation and Research Center for Geographical Information Technologies PostGIS Web-Server API Services!")

# View 2: Default alert message.
def alert_view(request):
	return HttpResponse("This is an alert message generated by ""postgis"" app")

# View 3: Sample connection to default Db
def defaultdb_view(request):
	cursor = connection.cursor()
	cursor.execute("select count(*) from world")
	result = []
	for i in cursor:
		row = {'count': i[0]}
		result.append(row)
	json_result = simplejson.dumps(result)
	return HttpResponse(json_result)

# View 4: Sample connection to dbconn1 Db
def dbconn1_view(request):
	cursor = connections['dbconn1'].cursor()
	cursor.execute("select count(*) from world")
	result = []
	for i in cursor:
		row = {'count': i[0]}
		result.append(row)
	json_result = simplejson.dumps(result)
	return HttpResponse(json_result)
